apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # Assuming your Pods are listening on port 80
  type: LoadBalancer




